# 去application.yml里配置active: test就可以运行本地test环境
server:
  port: 8080
  servlet:
    context-path: /diancan
spring:
  datasource:
    url: jdbc:mysql://localhost/diancan?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
      &useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: 1128
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
